// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/signin": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/goals": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/signin" | "/dashboard" | "/dashboard/goals";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/";
  };
  "routes/signin.tsx": {
    id: "routes/signin";
    page: "/signin";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard" | "/dashboard/goals";
  };
  "routes/goals.tsx": {
    id: "routes/goals";
    page: "/dashboard/goals";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/signup": typeof import("./app/routes/signup.tsx");
  "routes/signin": typeof import("./app/routes/signin.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/goals": typeof import("./app/routes/goals.tsx");
};